In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [2]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
df.drop(columns='Id',inplace = True)

In [4]:
x = df.drop(columns='Species')
y = df['Species']

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [10]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc_scr = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print(f"Accuracy:{acc_scr}")
print(f"CM:{cm}")

diff = pd.DataFrame(np.c_[y_test,y_pred],columns=["Actual value","Predicted values"])
diff

Accuracy:1.0
CM:[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Actual value Predicted values
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26   Iris-virginica   Iris-virginica
27   Iris-virginica   Iris-virginica
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa

In [11]:
from sklearn.ensemble import RandomForestClassifier

rfr = RandomForestClassifier()
rfr.fit(x_train,y_train)
y_pred = rfr.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix
acc_scr = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print(f"Accuracy:{acc_scr}")
print(f"CM:{cm}")

diff = pd.DataFrame(np.c_[y_test,y_pred],columns=["Actual value","Predicted values"])
diff

Accuracy:1.0
CM:[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Actual value Predicted values
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26   Iris-virginica   Iris-virginica
27   Iris-virginica   Iris-virginica
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa

In [12]:
import joblib
joblib.dump(lr,"lr_model.joblib")

['lr_model.joblib']

In [13]:
joblib.dump(sc,"sc_model.joblib")

['sc_model.joblib']